/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DiffTree: typeof import('./../components/DiffTree.vue')['default']
    JsonEditor: typeof import('./../components/JsonEditor.vue')['default']
    JsonInputArea: typeof import('./../components/JsonInputArea.vue')['default']
    MergePreview: typeof import('./../components/MergePreview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./../components/ThemeToggle.vue')['default']
  }
}
